<?php
# This file was automatically generated by the MediaWiki 1.34.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}
# 保护隐私起见，敏感内容已脱敏处理。建站时请注意补全。

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Zn Music";
$wgMetaNamespace = "Zn_Music";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";     


## The protocol and server name to use in fully-qualified URLs
$wgServer = "examp.le";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/znmusic-logo-150px.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "noreply@zhinengp.top";
$wgPasswordSender = "noreply@zhinengp.top";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "127.0.0.1";
$wgDBname = "DataBase";
$wgDBuser = "DataBase";
$wgDBpassword = "DataBase";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "zh";

$wgSecretKey = "SECRET KEY WILL GENERATE AUTOMATICALLY";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "UPGRADE KEY WILL GENERATE AUTOMATICALLY";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# 共享协议请按照实际情况自行选用。
# 在“三分钟建站”阶段，他会给你选择的地方的。
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-nc-sa/4.0/";
$wgRightsText = "知识共享署名-非商业性使用-相同方式共享";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;

## 这里选择默认主题，我用了''我认为''相对美观的Timeless
$wgDefaultSkin = "Timeless";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'vector' );
wfLoadSkin( 'monobook' );

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
# 虽说添加并保存后，这些插件就会启用，但某些插件还需要跑一下'php maintaince\update.php'
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'FontAwesome' );
wfLoadExtension( 'AbuseFilter' );
wfLoadExtension( 'AccountInfo' );
wfLoadExtension( 'CSS' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension('Avatar');
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'Comments' );
wfLoadExtension( 'CheckUser' );
wfLoadExtension( 'NativeSvgHandler' );
wfLoadExtension( 'TimedMediaHandler' );
wfLoadExtension('PinyinSort');
wfLoadExtension( 'AntiSpoof' );



# 以下是各个插件的config
# Add more configuration options below.
$wgSVGConverter = 'ImageMagick';

# The configuration of FontAwesome
$wgShowDebug = false;
$wgFaRenderMode = 'webfonts';

# The configuration of AbuseFilter
$wgGroupPermissions['sysop']['abusefilter-modify'] = true;
$wgGroupPermissions['user']['abusefilter-log-detail'] = true;
$wgGroupPermissions['user']['abusefilter-view'] = true;
$wgGroupPermissions['user']['abusefilter-log'] = true;
$wgGroupPermissions['sysop']['abusefilter-privatedetails'] = true;
$wgGroupPermissions['sysop']['abusefilter-modify-restricted'] = true;
$wgGroupPermissions['sysop']['abusefilter-revert'] = true; 

# The configuration of CSS
$wgCSSPath = '//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css';

# The configuration of Thanks
$wgThanksSendToBots = false;
$wgThanksLogging = true;
$wgThanksConfirmationRequired = true;
$wgThanksLogTypeWhitelist = [
	"contentmodel",
	"delete",
	"import",
	"merge",
	"move",
	"patrol",
	"protect",
	"tag",
	"managetags",
	"rights"
];

# The configuration of Gadgets
$wgGroupPermissions['interface-admin']['gadgets-edit'] = true;
$wgGroupPermissions['interface-admin']['gadgets-definition-edit'] = true;

# The configuration of VisualEditor
$wgVisualEditorEnableWikitext = true;
$wgDefaultUserOptions['visualeditor-newwikitext'] = 0;
$wgHiddenPrefs[] = 'visualeditor-newwikitext';
$wgVisualEditorEnableWikitext = true;

# The configuration of Comments
$wgGroupPermissions['sysop']['commentadmin'] = true;
$wgGroupPermissions['user']['commentlinks'] = true;
$wgGroupPermissions['user']['comment'] = true;

# The configuration of CheckUser
$wgGroupPermissions['sysop']['checkuser'] = true;
$wgGroupPermissions['sysop']['checkuser-log'] = true;

# The configuration of TimedMediaHandler
$wgFFmpegLocation = 'C:\Users\Administrator\Desktop\ffmpeg-4.2.2';

# The configuration of PinyinSort
$wgCategoryCollation = 'pinyin';

# The configuration of AntiSpoof
$wgSharedTables[] = 'spoofuser';

# Enable Semantic MediaWiki
#require_once( "/extensions/Validator/Validator.php" );
#include_once( "/extensions/SemanticMediaWiki/SemanticMediaWiki.php" );
#enableSemantics('39.97.223.6:82');
